Directory:
  exp_name: 'bs16_defaultIMUEncoder_withBN'
  data_dir: ./data
  log_dir: ./tensorboard
  weights: ./weights

Train:
  img_w: 832
  img_h: 256
  v_f_len: 512
  i_f_len: 256
  imu_dropout: 0.2
  rnn_hidden_size: 512 #1024
  rnn_dropout: 0.2 #0.2
  weight_decay: 0.
  batch_size: 4 # 1
  seq_len: 11
  epoch: 101
  epochs_warmup: 30
  epochs_joint: 80
  init_lr: 0.0002